[package]
name = "todo-txt"
version = "1.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
description = "Parser for the todo.txt format"
license = "MIT"
keywords = ["parser", "todotxt"]
repository = "https://github.com/sanpii/todo-txt"
readme = "README.md"

[dependencies]
chrono = "^0.4"
lazy_static = "1.0.0"
nom = "^4.0"
regex = "^1.0"

[dependencies.clippy]
version = "^0.0"
optional = true

[badges]
travis-ci = { repository = "sanpii/todo-txt", branch = "master" }
gitlab = { repository = "sanpi/todo-txt", branch = "master" }
